import { expect, test } from '@playwright/test'

test('domestic liquidity dashboard is the first page and light theme is default', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.getByTestId('liquidity-dashboard')).toBeVisible()
  await expect(page.getByRole('heading', { name: '국내 증시 자금 상태' })).toBeVisible()
  await expect(page.getByRole('button', { name: '시장 데이터 수동 새로고침' })).toBeVisible()
  await expect(page.getByText('TOP100 누적 거래대금', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: '증시 주변자금 · 대기자금 · 레버리지' })).toBeVisible()
  await expect(page.getByText('투자자예탁금', { exact: true })).toBeVisible()
  await expect(page.getByText('신용융자 잔고', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('liquidity-dashboard.png'), fullPage: true })
})

test('domestic theme flow board, feature news and top100 rail render', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: '국내 테마 흐름' }).click()
  await expect(page.getByTestId('feature-news')).toBeVisible()
  await expect(page.getByRole('heading', { name: '특징주 이슈' })).toBeVisible()
  await expect(page.getByTestId('theme-strength-board')).toBeVisible()
  await expect(page.getByRole('heading', { name: /테마 강도 비교/ })).toBeVisible()
  await expect(page.getByText('TOP50 내 3종+')).toBeVisible()
  await expect(page.getByText(/3분 평균 \+ 1시간 눈금/)).toBeVisible()
  await expect(page.getByTestId('top100-ranking')).toBeVisible()
  await expect(page.getByRole('heading', { name: '거래대금 TOP100' })).toBeVisible()

  const details = page.locator('.deep-market-details')
  await details.locator(':scope > summary').click()
  await expect(page.getByTestId('moneyflow-dashboard')).toBeVisible()
  await expect(page.getByRole('heading', { name: '한국 시장 전체 Heatmap' })).toBeVisible()

  await page.screenshot({ path: testInfo.outputPath('theme-flow-dashboard.png'), fullPage: true })
})

test('US theme flow page is available', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: '미국 테마 흐름' }).click()
  await expect(page.getByTestId('us-theme-strength-board')).toBeVisible()
  await expect(page.getByRole('heading', { name: /미국 테마 강도 비교/ })).toBeVisible()
  await expect(page.getByText('미국 TOP50 내 3종+')).toBeVisible()
  await expect(page.getByTestId('us-top100-ranking')).toBeVisible()
  await expect(page.getByRole('heading', { name: '미국 거래대금 TOP100' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('us-theme-flow-dashboard.png'), fullPage: true })
})

test('stock quiz separates full KOSPI200 and KOSDAQ150 company-description pools', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '종목 퀴즈' }).click()
  await expect(page.getByTestId('index-quiz')).toBeVisible()
  await expect(page.getByRole('heading', { name: /어느 시장의 기업을 더 많이 알고 있을까/ })).toBeVisible()
  await expect(page.getByTestId('quiz-pool-kospi200')).toContainText('KOSPI 200')
  await expect(page.getByTestId('quiz-pool-kosdaq150')).toContainText('KOSDAQ 150')
  await expect(page.getByText('ETF·ETN 제외', { exact: true })).toBeVisible()

  await page.getByTestId('quiz-pool-kospi200').click()
  await expect(page.getByTestId('question-card')).toBeVisible()
  await expect(page.getByTestId('question-card')).toContainText('기업 설명')
  await expect(page.locator('.index-quiz-choices button')).toHaveCount(4)
})

test('pages have no horizontal overflow', async ({ page }) => {
  await page.goto('/')
  let sizes = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(sizes.scrollWidth).toBeLessThanOrEqual(sizes.clientWidth + 1)
  await page.getByRole('button', { name: '국내 테마 흐름' }).click()
  sizes = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(sizes.scrollWidth).toBeLessThanOrEqual(sizes.clientWidth + 1)
  await page.getByRole('button', { name: '미국 테마 흐름' }).click()
  sizes = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(sizes.scrollWidth).toBeLessThanOrEqual(sizes.clientWidth + 1)
  await page.getByRole('button', { name: '종목 퀴즈' }).click()
  sizes = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(sizes.scrollWidth).toBeLessThanOrEqual(sizes.clientWidth + 1)
})
